# Generated by Django 5.1.5 on 2025-02-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0002_alter_shoe_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='stock',
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shoe.shoe')),
            ],
        ),
    ]
